### ISSUE TITLE
您好，有一个问题是，为什么网络中没有判别器，那我生成器生成的图片质量会不会受到影响，或者说判别器的作用在哪里体现？

### ISSUE THREAD

**Issue by Lion-CTGU** [Gilgamesh-qx/FrScatNet#1]

**Comment by XiangQiu42** [comment]
Sorry for the late response.

Actually, we have no discriminator, for more details, you can refer to our paper   [Fractional Wavelet-Based Generative Scattering Networks](https://www.frontiersin.org/articles/10.3389/fnbot.2021.752752/full).

**Comment by Lion-CTGU** [comment]
ok, thanks for your reply. have a good day.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "XiangQiu42/FrScatNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月15日(星期一) 下午4:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [XiangQiu42/FrScatNet] 您好，有一个问题是，为什么网络中没有判别器，那我生成器生成的图片质量会不会受到影响，或者说判别器的作用在哪里体现？ (Issue #1)





 
Sorry for the late response.
 
Actually, we have no discriminator, for more details, you can refer to our paper   Fractional Wavelet-Based Generative Scattering Networks.
